/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author 396301368
 */
public class question1 extends javax.swing.JFrame {

    int vida = 3, score = 0, i = 0;

    /**
     * Creates new form question1
     */
    public question1() {
        initComponents();

        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        titulo.setVisible(false);

        jButton1.setText("começar");
        pergunta.setText("Aperte o botão para começar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pontos = new javax.swing.JLabel();
        lblVidas = new javax.swing.JLabel();
        pergunta = new javax.swing.JLabel();
        a = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        c = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 0));
        titulo.setText("Questão 1");
        getContentPane().add(titulo);
        titulo.setBounds(340, 120, 150, 50);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Vidas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 60, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Pontos:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(620, 30, 70, 40);

        pontos.setBackground(new java.awt.Color(255, 255, 255));
        pontos.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        pontos.setForeground(new java.awt.Color(255, 255, 0));
        pontos.setText("0");
        getContentPane().add(pontos);
        pontos.setBounds(700, 30, 40, 40);

        lblVidas.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblVidas.setForeground(new java.awt.Color(255, 255, 0));
        lblVidas.setText("3");
        getContentPane().add(lblVidas);
        lblVidas.setBounds(90, 30, 20, 30);

        pergunta.setBackground(new java.awt.Color(255, 255, 255));
        pergunta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pergunta.setForeground(new java.awt.Color(255, 255, 0));
        pergunta.setText("O HTML é uma linguagem de :");
        getContentPane().add(pergunta);
        pergunta.setBounds(70, 240, 740, 40);

        buttonGroup1.add(a);
        a.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        a.setText("Programação");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(110, 290, 710, 31);

        buttonGroup1.add(b);
        b.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        b.setText("Estilização");
        getContentPane().add(b);
        b.setBounds(110, 320, 710, 31);

        buttonGroup1.add(c);
        c.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        c.setText("Consulta Estruturada");
        getContentPane().add(c);
        c.setBounds(110, 350, 710, 31);

        buttonGroup1.add(d);
        d.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        d.setText("Marcação de HiperTexto");
        getContentPane().add(d);
        d.setBounds(110, 380, 710, 31);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Próxima");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 440, 110, 40);

        background.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/devBG.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-50, -20, 900, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        i++;

        switch (i) {
            case 1:
                a.setVisible(true);
                b.setVisible(true);
                c.setVisible(true);
                d.setVisible(true);
                titulo.setVisible(true);
                jButton1.setText("próximo");

                pergunta.setText("O HTML é uma linguagem de :");
                a.setText("Programação");
                b.setText("Consulta Estruturada");
                c.setText("Marcação de HiperTexto");
                d.setText("Estilização");
                break;
            case 2:
                if (!c.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 2");

                pergunta.setText("Quem criou a World Wide Web?");
                a.setText("Steve Jobs");
                b.setText("Tim Barners-Lee");
                c.setText("Linus Torvalds");
                d.setText("Bill Gates");

                break;

            case 3:
                if (!b.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 3");

                pergunta.setText("Qual das alternativas abaixo não é um SGBD?");
                a.setText("MySQL");
                b.setText("SQL Server");
                c.setText("MariaDB");
                d.setText("MySQL WorkBench");

                break;
            case 4:
                if (!d.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 4");

                pergunta.setText("IF é:");
                a.setText("Laço de Repetição");
                b.setText("Estrutura condicional");
                c.setText("Operador lógico");
                d.setText("Tag HTML");

                break;
            case 5:
                if (!b.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 5");

                pergunta.setText("O que é GitHub?");
                a.setText("Sistema de versionamento distribuido");
                b.setText("Linguagem de programação");
                c.setText("Sistema de versionamento centralizado");
                d.setText("Repositório Online");

                break;
            case 6:
                if (!d.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 6");

                pergunta.setText("Linus Torvalds criou o ...");
                a.setText("Linux");
                b.setText("MacOS");
                c.setText("Windows");
                d.setText("Android");

                break;
            case 7:
                if (!a.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 7");

                pergunta.setText("Em qual ano foi lançado o GIT");
                a.setText("2010");
                b.setText("1972");
                c.setText("2005");
                d.setText("2000");

                break;
            case 8:
                if (!c.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 8");

                pergunta.setText("IONIC é :");
                a.setText("IDE");
                b.setText("Framework");
                c.setText("Linguagem de programação");
                d.setText("Sistema operacional");

                break;
            case 9:
                if (!b.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 9");

                pergunta.setText("Qual empresa desenvolveu o Java :");
                a.setText("Microsoft");
                b.setText("Oracle");
                c.setText("IBM");
                d.setText("Sun Microsystems");

                break;
            case 10:
                if (!d.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }

                titulo.setText("Questão 10");

                pergunta.setText("Mark Zuckerberg criou o :");
                a.setText("Instagram");
                b.setText("Whatsapp");
                c.setText("Facebook");
                d.setText("Twitter");

                break;
            case 11:
                if (!c.isSelected()) {
                    vida = vida - 1;
                    lblVidas.setText(Integer.toString(vida));

                } else {
                    score = score + 10;
                    pontos.setText(Integer.toString(score));
                }
                if (vida == 0) {
                    JOptionPane.showMessageDialog(null, "GameOver");
                    System.exit(0);
                }
            default:
                a.setVisible(false);
                b.setVisible(false);
                c.setVisible(false);
                d.setVisible(false);
                titulo.setVisible(false);

                jButton1.setVisible(false);
                pergunta.setVisible(false);
                
                JOptionPane.showMessageDialog(null, "Você ganhou");
                    System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton b;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton c;
    private javax.swing.JRadioButton d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblVidas;
    private javax.swing.JLabel pergunta;
    private javax.swing.JLabel pontos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
